// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./src/renderer/components/CommonHeader/CommonHeader.vue')['default']
    CommonList: typeof import('./src/renderer/components/CommonList/CommonList.vue')['default']
    CommonSongList: typeof import('./src/renderer/components/biz/CommonSongList.vue')['default']
    EmptyMusic: typeof import('./src/renderer/components/EmptyMusic/EmptyMusic.vue')['default']
    LoginRegisterModal: typeof import('./src/renderer/components/LoginRegisterModal/LoginRegisterModal.vue')['default']
    MIcon: typeof import('./src/renderer/components/MIcon/MIcon.vue')['default']
    MusicLogo: typeof import('./src/renderer/components/MusicLogo/MusicLogo.vue')['default']
    PlayerArea: typeof import('./src/renderer/components/PlayerArea/PlayerArea.vue')['default']
    PlayerBar: typeof import('./src/renderer/components/PlayerBar/PlayerBar.vue')['default']
    ProgressBar: typeof import('./src/renderer/components/ProgressBar/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongSearchResult: typeof import('./src/renderer/components/SongSearchResult/SongSearchResult.vue')['default']
  }
}
